# Terraform Outputs
# Generates data for Ansible inventory and documentation

# =============================================================================
# Container Information
# =============================================================================

output "container_ips" {
  description = "Map of container names to IP addresses"
  value = {
    for name, container in proxmox_lxc.containers : name => container.network[0].ip
  }
}

output "container_ids" {
  description = "Map of container names to VMIDs"
  value = {
    for name, container in proxmox_lxc.containers : name => container.vmid
  }
}

# =============================================================================
# Ansible Inventory Output
# =============================================================================

output "ansible_inventory" {
  description = "Ansible inventory in INI format"
  value = <<-EOT
# Ansible Inventory - Generated by Terraform
# Do not edit manually - regenerate with: terraform output -raw ansible_inventory > ../ansible/inventory/hosts.ini

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3

[core]
%{for name, container in proxmox_lxc.containers~}
%{if contains(split(";", container.tags), "core")~}
${container.hostname} ansible_host=${split("/", container.network[0].ip)[0]}
%{endif~}
%{endfor~}

[apps]
%{for name, container in proxmox_lxc.containers~}
%{if contains(split(";", container.tags), "apps")~}
${container.hostname} ansible_host=${split("/", container.network[0].ip)[0]}
%{endif~}
%{endfor~}

[monitoring]
%{for name, container in proxmox_lxc.containers~}
%{if contains(split(";", container.tags), "monitoring")~}
${container.hostname} ansible_host=${split("/", container.network[0].ip)[0]}
%{endif~}
%{endfor~}

[dev]
%{for name, container in proxmox_lxc.containers~}
%{if contains(split(";", container.tags), "dev")~}
${container.hostname} ansible_host=${split("/", container.network[0].ip)[0]}
%{endif~}
%{endfor~}

[security]
%{for name, container in proxmox_lxc.containers~}
%{if contains(split(";", container.tags), "security")~}
${container.hostname} ansible_host=${split("/", container.network[0].ip)[0]}
%{endif~}
%{endfor~}
EOT
}

# =============================================================================
# JSON Output for External Tools
# =============================================================================

output "containers_json" {
  description = "All container information in JSON format"
  value = jsonencode({
    for name, container in proxmox_lxc.containers : name => {
      vmid     = container.vmid
      hostname = container.hostname
      ip       = split("/", container.network[0].ip)[0]
      cores    = container.cores
      memory   = container.memory
      tags     = split(";", container.tags)
    }
  })
}

# =============================================================================
# Documentation Output
# =============================================================================

output "inventory_markdown" {
  description = "Container inventory in Markdown format for documentation"
  value = <<-EOT
# LXC Inventory (Generated)

| ID | Hostname | IP Address | Cores | Memory | Tags |
|----|----------|------------|-------|--------|------|
%{for name, container in proxmox_lxc.containers~}
| ${container.vmid} | ${container.hostname} | ${split("/", container.network[0].ip)[0]} | ${container.cores} | ${container.memory}MB | ${container.tags} |
%{endfor~}
EOT
}
